In [2]:
import numpy as np

In [2]:
np.__version__

'2.4.4'

## Create & Read

In [3]:
# esc , m , shift+return

In [4]:
## big text size , #### small text size

#### 1D Array

In [5]:
arr1 = np.array([1, 2, 3, 4, 5])

In [6]:
arr1


array([1, 2, 3, 4, 5])

In [7]:
type(arr1)

numpy.ndarray

In [17]:
arr1.shape   # check rows and colums    --> (rows,columns)

(5,)

In [10]:
arr1.dtype

dtype('int64')

In [11]:
arr1.ndim   # check which dimension array (1D, 2D , etc.)

1

In [12]:
arr1.size    # check size of array

5

#### 2D Array

In [13]:
arr2 = np.array([[1, 4, 5], [6, 7 ,4]])
arr2

array([[1, 4, 5],
       [6, 7, 4]])

In [14]:
# Above , Rows and Column

In [15]:
arr2.ndim    # check Dimension

2

In [16]:
arr2.shape # (row, col)

(2, 3)

In [18]:
arr2.dtype

dtype('int64')

In [20]:
arr2.size   # numbers of an array

6

#### 3D Array

In [7]:
arr3 = np.array([  [ [1, 4, 5], [6, 7, 4] ],    [ [3, 5, 4], [5, 8, 7] ]   ])

In [4]:
arr3

array([[[1, 4, 5],
        [6, 7, 4]],

       [[3, 5, 4],
        [5, 8, 7]]])

In [5]:
arr3.ndim

3

In [6]:
arr3.shape      # (2 layer , rows in 1 st layer , columns in )

(2, 2, 3)

In [8]:
arr4 = np.array([  [ [1, 4, 5], [6, 7, 4] ],    [ [3, 5, 4], [5, 8, 7] ] ,  [ [1, 4, 5], [6, 7, 4] ]   ])

In [9]:
arr4

array([[[1, 4, 5],
        [6, 7, 4]],

       [[3, 5, 4],
        [5, 8, 7]],

       [[1, 4, 5],
        [6, 7, 4]]])

In [10]:
arr3.ndim

3

In [13]:
arr3.shape      

(2, 2, 3)

### Create Random Array

In [16]:
randomArr = np.random.rand(3, 2, 3)    # 3-layer,2 layer in 1st layer, 3 columns in 1st layer

In [17]:
randomArr

array([[[0.86508896, 0.34940368, 0.8814543 ],
        [0.73486526, 0.27427643, 0.04934453]],

       [[0.55219263, 0.0518432 , 0.3072985 ],
        [0.59238601, 0.91298047, 0.90743627]],

       [[0.28655661, 0.82083926, 0.4767697 ],
        [0.09798895, 0.08861807, 0.52837778]]])

In [18]:
randomArr.dtype

dtype('float64')

#### Zeros

In [23]:
zeros = np.zeros((3, 2, 3))

In [24]:
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [25]:
zeros.ndim

3

#### full 

In [26]:
full = np.full((3, 2, 3), 8)     # shapes (3, 2, 3)  ,, 8 is Number to print

In [27]:
full

array([[[8, 8, 8],
        [8, 8, 8]],

       [[8, 8, 8],
        [8, 8, 8]],

       [[8, 8, 8],
        [8, 8, 8]]])

#### Ones 

In [29]:
ones = np.ones((3, 2, 3))

In [30]:
ones

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

### Operation

In [32]:
arr4

array([[[1, 4, 5],
        [6, 7, 4]],

       [[3, 5, 4],
        [5, 8, 7]],

       [[1, 4, 5],
        [6, 7, 4]]])

In [33]:
arr4[0]   # 1st layer

array([[1, 4, 5],
       [6, 7, 4]])

In [34]:
arr4[0,0]  # 1st row of 1st layer

array([1, 4, 5])

In [35]:
arr4[0,0,0]  # 1 number of row in 1st layer

np.int64(1)

In [36]:
arr4[0,0,2]

np.int64(5)

#### Slice operation

In [38]:
arr4

array([[[1, 4, 5],
        [6, 7, 4]],

       [[3, 5, 4],
        [5, 8, 7]],

       [[1, 4, 5],
        [6, 7, 4]]])

In [39]:
arr4[0:2]    # not include 3rd layer

array([[[1, 4, 5],
        [6, 7, 4]],

       [[3, 5, 4],
        [5, 8, 7]]])

In [40]:
arr4

array([[[1, 4, 5],
        [6, 7, 4]],

       [[3, 5, 4],
        [5, 8, 7]],

       [[1, 4, 5],
        [6, 7, 4]]])

In [41]:
arr4[-1]    # last layer 

array([[1, 4, 5],
       [6, 7, 4]])

In [42]:
arr4

array([[[1, 4, 5],
        [6, 7, 4]],

       [[3, 5, 4],
        [5, 8, 7]],

       [[1, 4, 5],
        [6, 7, 4]]])

In [43]:
arr4[1][1][1]

np.int64(8)

In [44]:
arr4

array([[[1, 4, 5],
        [6, 7, 4]],

       [[3, 5, 4],
        [5, 8, 7]],

       [[1, 4, 5],
        [6, 7, 4]]])

In [45]:
arr4[1][0][1]

np.int64(5)

### Update & Delete

In [46]:
a1 = np.random.rand(2, 3, 2)
a2 = np.random.rand(2, 3, 2)

In [47]:
a1

array([[[0.12460379, 0.4933514 ],
        [0.83958867, 0.49504583],
        [0.68515544, 0.46190898]],

       [[0.84019708, 0.53372384],
        [0.87145833, 0.79639696],
        [0.43077853, 0.35810184]]])

In [48]:
a2

array([[[0.99956845, 0.78504083],
        [0.90846156, 0.39654385],
        [0.2565317 , 0.33562703]],

       [[0.91577504, 0.7328051 ],
        [0.04080773, 0.20859499],
        [0.63223444, 0.79809709]]])

#### Basic Math Operations

In [49]:
np.add(a1,a2)

array([[[1.12417224, 1.27839223],
        [1.74805023, 0.89158967],
        [0.94168713, 0.79753601]],

       [[1.75597212, 1.26652894],
        [0.91226606, 1.00499195],
        [1.06301297, 1.15619893]]])

In [50]:
np.subtract(a1,a2)

array([[[-0.87496466, -0.29168943],
        [-0.06887289,  0.09850198],
        [ 0.42862374,  0.12628194]],

       [[-0.07557796, -0.19908126],
        [ 0.8306506 ,  0.58780197],
        [-0.20145591, -0.43999524]]])

In [51]:
np.divide(a1,a2)

array([[[ 0.12465759,  0.62844044],
        [ 0.92418733,  1.24840122],
        [ 2.67084126,  1.37625678]],

       [[ 0.91747104,  0.72832986],
        [21.35522515,  3.81791034],
        [ 0.68135885,  0.44869459]]])

In [52]:
np.multiply(a1,a2)

array([[[0.12455002, 0.38730099],
        [0.76273403, 0.19630738],
        [0.17576409, 0.15502914]],

       [[0.76943152, 0.39111555],
        [0.03556224, 0.16612442],
        [0.27235302, 0.28580004]]])

#### Statistical Operations

In [58]:
a1 , a2

(array([[[0.12460379, 0.4933514 ],
         [0.83958867, 0.49504583],
         [0.68515544, 0.46190898]],
 
        [[0.84019708, 0.53372384],
         [0.87145833, 0.79639696],
         [0.43077853, 0.35810184]]]),
 array([[[0.99956845, 0.78504083],
         [0.90846156, 0.39654385],
         [0.2565317 , 0.33562703]],
 
        [[0.91577504, 0.7328051 ],
         [0.04080773, 0.20859499],
         [0.63223444, 0.79809709]]]))

In [54]:
sqrt = np.sqrt(25)         #square root
abs = np.abs(-2)           # absolute value
power = np.power(2,8)      # power  ( 2to the power of 8)
log = np.log(25)           # log
mins = np.min(a1)          # minimum element value
maxs = np.max(a2)          # maximum element value

In [55]:
sqrt

np.float64(5.0)

In [56]:
sqrt,abs

(np.float64(5.0), np.int64(2))

In [57]:
sqrt, abs, power, log, mins, maxs    # all answers

(np.float64(5.0),
 np.int64(2),
 np.int64(256),
 np.float64(3.2188758248682006),
 np.float64(0.1246037906161589),
 np.float64(0.9995684483763095))

#### Update 

In [59]:
arr4

array([[[1, 4, 5],
        [6, 7, 4]],

       [[3, 5, 4],
        [5, 8, 7]],

       [[1, 4, 5],
        [6, 7, 4]]])

In [60]:
arr4[0,0,2] = 500    # Replace the number

In [61]:
arr4

array([[[  1,   4, 500],
        [  6,   7,   4]],

       [[  3,   5,   4],
        [  5,   8,   7]],

       [[  1,   4,   5],
        [  6,   7,   4]]])

In [62]:
arr4.sort()  # Sort in a row

In [63]:
arr4

array([[[  1,   4, 500],
        [  4,   6,   7]],

       [[  3,   4,   5],
        [  5,   7,   8]],

       [[  1,   4,   5],
        [  4,   6,   7]]])

### Reshape

In [64]:
arr4

array([[[  1,   4, 500],
        [  4,   6,   7]],

       [[  3,   4,   5],
        [  5,   7,   8]],

       [[  1,   4,   5],
        [  4,   6,   7]]])

In [65]:
arr4.shape

(3, 2, 3)

In [66]:
arr4_reshape = arr4.reshape((2, 3, 3))     # reshape (3, 2, 3) To (2, 3, 3)

In [67]:
arr4_reshape

array([[[  1,   4, 500],
        [  4,   6,   7],
        [  3,   4,   5]],

       [[  5,   7,   8],
        [  1,   4,   5],
        [  4,   6,   7]]])

In [68]:
arr4_reshape.shape

(2, 3, 3)

In [70]:
arr4_reshape_1 = arr4.reshape((2, 3, -1))   # last 3 is not nessesory

In [71]:
arr4_reshape_1

array([[[  1,   4, 500],
        [  4,   6,   7],
        [  3,   4,   5]],

       [[  5,   7,   8],
        [  1,   4,   5],
        [  4,   6,   7]]])

### Appending & Inserting

In [72]:
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [74]:
new_array = np.ones((3, 2, 3))

In [75]:
new_array

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [76]:
appd = np.append(zeros, new_array, axis=0) # axis 0 = row ,, axis 1 =column

In [77]:
appd

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [78]:
appd_1 = np.append(zeros, new_array, axis=0)  # row

In [79]:
appd_1 

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [80]:
appd_2 = np.append(zeros, new_array, axis=1)  # column

In [81]:
appd_2

array([[[0., 0., 0.],
        [0., 0., 0.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [1., 1., 1.],
        [1., 1., 1.]]])

#### Insert

In [83]:
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [84]:
new_array

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [86]:
inserted_array = np.insert(zeros, 1 , new_array , axis=0)   # 1 is index

In [87]:
inserted_array

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [88]:
inserted_array_1 = np.insert(zeros, 2 , new_array , axis=0)  # index 2

In [89]:
inserted_array_1

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

#### Delete Array

In [90]:
arr5 = np.random.rand(3, 2, 3)

In [91]:
arr5

array([[[0.04748894, 0.62681635, 0.95213969],
        [0.21482103, 0.10735129, 0.19611918]],

       [[0.32694849, 0.24473847, 0.37854261],
        [0.4833188 , 0.47964333, 0.6695064 ]],

       [[0.19507147, 0.77176534, 0.59178831],
        [0.64062494, 0.14406445, 0.12898838]]])

In [94]:
arr6 = np.delete(arr5, 0, axis=1)   # 0th index row delete each layers

In [93]:
arr6

array([[[0.21482103, 0.10735129, 0.19611918]],

       [[0.4833188 , 0.47964333, 0.6695064 ]],

       [[0.64062494, 0.14406445, 0.12898838]]])

In [97]:
# To save array into a file , filename "After_delete_Array"
np.save("After_delete_Array", arr6)

In [100]:
np.load("After_delete_Array.npy")

array([[[0.21482103, 0.10735129, 0.19611918]],

       [[0.4833188 , 0.47964333, 0.6695064 ]],

       [[0.64062494, 0.14406445, 0.12898838]]])